# Python for Scientists - 2023/2024

Gunar Stevens

# Chapter 1 - Numerical limitations

😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨😨

# Chapter 2 - Numerical linear algebra

## 2.1 - Systems of linear equations

### 2.1.1. Notations and Terminology

A system of $m$ equations with $n$ variables can be written as:
\begin{cases}
a_{11}x_1+a_{12}x_2+...+a_{1n}x_n = b_1\\
a_{21}x_1+a_{22}x_2+...+a_{2n}x_n = b_2\\
\vdots\\
a_{m1}x_1+a_{m2}x_2+...+a_{mn}x_n = b_n\\
\end{cases}
\
Or in equivalent matrix form:
$\begin{bmatrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m1}&a_{m2}&...&a_{mn}\\
\end{bmatrix}\begin{bmatrix}
x_1\\x_2\\\vdots\\x_n
\end{bmatrix} = \begin{bmatrix}
b_1\\b_2\\\vdots\\b_n
\end{bmatrix}$

A nxn matrix $\textsf{A}$ is called **non-singular** if:
- $\textsf{A}$ has an inverse $\textsf{A}^{-1}$ such that $\textsf{A}^{-1}$$\textsf{A} = \textsf{I}_n$
- det($\textsf{A}$) = 0
- rank($\textsf{A}$) = n
- For any vector $\textsf{z} \neq 0$, $\textsf{Az}$ must also be nonzero.

If $\textsf{A}$ is non-singular, it always has a unique solution for any $\textsf{b} \in \mathbb{R}^n$ in: $\textsf{Ax = b}$

### 2.1.2. LU factorization/ Gaussian elimination

#### Manual computation and Theoretical background

We want to transform our linear system into a **triangular linear system**, given a non-singular matrix $\textsf{M}$ and the equation-to-solve $\textsf{Ax = b}$, multiplying(left matrix multiplication) both sides by $\textsf{M}$ yields the form $\textsf{MAx = Mb}$, which has the same solution as the original system. We are to transform $\textsf{A}$ into either a lower triangular matrix(a matrix where all the elements above the diagonal are zero), or upper triangular matrix(a matrix where all the elements below the diagonal are zero), and so we need to find the $\textsf{M}$ that realises this.

Generally speaking, for a $n$-vector **a**(the *$k$*th column in our matrix $\textsf{A}$), we can annihilate all of its entries below the *$k$*th position (assuming $a_k \neq 0$) by the following transformation:

$\textsf{M}_{ka}=
\begin{bmatrix}
1&...&0&0&...&0\\
\vdots&\ddots&\vdots&\vdots&\ddots&\vdots\\
0&...&1&0&...&0\\
0&...&-m_{k+1}&1&...&0\\
\vdots&\ddots&\vdots&\vdots&\ddots&\vdots\\
0&...&-m_n&0&...&1
\end{bmatrix}\begin{bmatrix}
a_1\\\vdots\\a_k\\a_{k+1}\\\vdots\\a_n
\end{bmatrix} = \begin{bmatrix}
a_1\\\vdots\\a_k\\0\\\vdots\\0
\end{bmatrix}
$

with $m_i = \frac{a_i}{a_k}$, $i = k+1,...,n$

Here, $a_k$ is called the **pivot**, this very transformation is what one would call a **Gauss transformation**. After finding  $\textsf{M}_{k}$ for every $k$ columns, the equations becomes:
$\textsf{M}_1\textsf{M}_2...\textsf{M}_k\textsf{A}$**x** $= $$\textsf{M}_1\textsf{M}_2...\textsf{M}_k$**b**, where $\textsf{M}_1\textsf{M}_2...\textsf{M}_k\textsf{A}$ is an upper triangular matrix $\textsf{U}$, which makes the system easy to solve. $\textsf{M}$ takes a similar form to 'craft' the lower triangular matrix $\textsf{L}$, the difference is that the $m$-elements will be above the diagonal.

One can write $\textsf{Ax = b}$ as $\textsf{LUx = b}$, where $\textsf{A = LU}$.

#### Python

Import necessary libraries

In [ ]:
import numpy as np
from scipy import linalg
from scipy.linalg import cho_solve, cholesky, inv, lu_factor, lu_solve, norm

Given matrix $\textsf{A}$ and vector **b**:

In [ ]:
A = np.array([[1, 1/2, 1/3, 1/4, 1/5, 1/6],
              [1/2, 1/3, 1/4, 1/5, 1/6, 1/7],
              [1/3, 1/4, 1/5, 1/6, 1/7, 1/8],
              [1/4, 1/5, 1/6, 1/7, 1/8, 1/9],
              [1/5, 1/6, 1/7, 1/8, 1/9, 1/10],
              [1/6, 1/7, 1/8, 1/9, 1/10, 1/11]])

b = np.array([1, 2, 3, 4, 5, 6])

Utilise scipy's linalg.lu method on $\textsf{A}$ to get the upper and lower triangular matrix, this is only necessary if one is interested in these matrices;

In [ ]:
L, U = linalg.lu(A, permute_l=True)
print("L:")
print(L)
print("U:")
print(U)

L:
[[ 1.          0.          0.          0.          0.          0.        ]
 [ 0.5         1.         -0.93333333  1.          0.          0.        ]
 [ 0.33333333  1.          0.          0.          0.          0.        ]
 [ 0.25        0.9         0.56       -0.21428571  1.          0.        ]
 [ 0.2         0.8         0.85333333 -0.14285714  0.88888889  1.        ]
 [ 0.16666667  0.71428571  1.          0.          0.          0.        ]]
U:
[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01  1.66666667e-01]
 [ 0.00000000e+00  8.33333333e-02  8.88888889e-02  8.33333333e-02
   7.61904762e-02  6.94444444e-02]
 [ 0.00000000e+00  0.00000000e+00  5.95238095e-03  9.92063492e-03
   1.22448980e-02  1.35281385e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  9.25925926e-04
   1.90476190e-03  2.70562771e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.04081633e-05 -5.15357658e-05]
 [ 0.00000000e+00  0.00000000e+00  0.0

To solve the system $\textsf{A}$**x**$=$**b**, we use scipy's linalg.solve;

In [ ]:
x = linalg.solve(A, b)
print(f'x = {x}')

x = [   -216.00000004    7350.00000122  -57120.00000835  166320.00002181
 -201600.00002412   85932.00000952]


See also: partial pivoting

### 2.1.3. Cholesky Factorization

#### Manual computation and Theoretical background

If a matrix $\textsf{A}$ is symmetric($\textsf{A}$ = $\textsf{A}^T$) and positive definite(**x**$^{\textsf{T}}\textsf{A}$**x**$>0$ for all **x** $\neq 0$) then we have $\textsf{U} = \textsf{L}^{\textsf{T}}$ where $\textsf{U}$ and $\textsf{L}$ are the upper and lower triangular matrix respectively, meaning that $\textsf{A} = \textsf{LL}^{\textsf{T}}$. Let's take a 2D example:

$\begin{bmatrix}
a_{11}&a_{12}\\
a_{21}&a_{22}\\
\end{bmatrix}=
\begin{bmatrix}
l_{11}&0\\l_{21}&l_{22}
\end{bmatrix}\begin{bmatrix}
l_{11}&l_{21}\\0&l_{22}
\end{bmatrix} = \begin{bmatrix}
l_{11}^2&l_{11}l_{21}\\
l_{11}l_{21}&l_{21}^2+l_{22}^2
\end{bmatrix}$

Implying that:
\begin{cases}
l_{11} = \sqrt{a_{11}}\\
l_{21} = a_{12}/l_{11}\\
l_{22} = \sqrt{a_{22} - l_{21}^2}
\end{cases}


#### Python

Import necessary libraries

In [ ]:
import numpy as np
from scipy import linalg
from scipy.linalg import cho_solve, cholesky, inv, lu_factor, lu_solve, norm

Given a positive-definite, symmetric matrix $\textsf{A}$ and vector **b**;

In [ ]:
A = np.array([
    [4,2,6],
    [2,2,5],
    [6,5,22]
])

b = np.array([1, 2, 3])

We can calculate the lower and upper triangular matrix using scipy's linalg.cholesky method:

In [ ]:
L_ , U_ = linalg.cholesky(A, lower=True), linalg.cholesky(A, lower=False)
#If lower = True, it will return the lower triangular matrix, if False, it will return the upper triangular matrix
print("L_:")
print(L_)
print("U_:")
print(U_)

L_:
[[2. 0. 0.]
 [1. 1. 0.]
 [3. 2. 3.]]
U_:
[[2. 1. 3.]
 [0. 1. 2.]
 [0. 0. 3.]]


In [ ]:
c,low = linalg.cho_factor(A,lower = True)
print(f'c = {c}')

c = [[2. 2. 6.]
 [1. 1. 5.]
 [3. 2. 3.]]


In [ ]:
x = linalg.cho_solve((c,low), b)
print(f'x = {x}')

x = [-0.41666667  1.83333333 -0.16666667]


### 2.1.4. Sensitivity and conditioning

#### Vector norms

**p-norm**, general form of the norms defind below:

$||$**x**$||$$_p$ $= (\sum^n_{i=1}||x_i||^p)^{1/p}$

**Manhattan norm** or 1-norm:

$||$**x**$||$$_1$ = $\sum^{n}_{i+1}||x_i||$

**Euclidean norm** or 2-norm:

$||$**x**$||$$_2$ = $\sqrt{\sum^n_{i=1}||x_i||^{2}}$

**$\infty$-norm** (thye limit for $p->∞$):

$||$**x**$||$$_{\infty}$ = max$||x_i||$ where $1\le i \le n$

Example; consider the vector **x** = $[-4,3]^{\textsf{T}}$

$||$**x**$||$$_1$ = 7

$||$**x**$||$$_2$ = 5

$||$**x**$||$$_{\infty}$ = 4

In general we get; $||$**x**$||$$_{\infty}$ $\le$ $||$**x**$||$$_2$ $\le$ $||$**x**$||$$_1$

#### Matrix norms

The norm of a $m \times n$ matrix $\textsf{A}$ is given by:

$||\textsf{A}|| =$ max$\frac{||\textsf{Ax}||}{||\textsf{x}||}$, where $\textsf{x} \neq 0$

Which corresponds with 'the maximum stretching' the matrix induces in a vector.

Two cases that are easy to calculate:

- $||\textsf{A}||_1$, which corresponds to the maximum absolute *column* sum of the matrix: $||\textsf{A}||_1 =$ max$_j \sum^m_{i=1}||a_{ij}||$

- $||\textsf{A}||_{\infty}$, which corresponds to the maximum absolute *row* sum of the matrix: $||\textsf{A}||_{\infty} =$ max$_{i} \sum^n_{j=1}||a_{ij}||$

#### Matrix Condition Number

The condition number of a nonsingular square matrix $\textsf{A}$ is defined as:

cond($\textsf{A}$) = $||\textsf{A}||\cdot||\textsf{A}^{-1}||$

By convention, the condition number of a singular matrix is $\infty$. The condition number can be interpreted as a measure of how close a matrix is to being singular.

#### Error Estimation

Consider a non-singular linear system $\textsf{Ax = b}$ with solution $\textsf{x}$. Also, let $\textsf{x'}$ be the solutiojn to the perturbed system $\textsf{Ax' = b} + \Delta \textsf{b}$, and define the difference between both solutions $\textsf{x'-x} = \Delta \textsf{x}$. Utilising norm properties and the definitions stated above, one can find:

$\frac{||\Delta \textsf{x}||}{||\textsf{x}||} \le$ cond$(\textsf{A})\frac{||\Delta \textsf{b}||}{||\textsf{b}||}$

The condition number thus acts as an "amplification factor" for the relative change in the solution with respect to a relative change in the right hand sided vector.

A similar inequality exists for deviations $\textsf{E}$ in matrix $\textsf{A}$, such that $(\textsf{A+E})\textsf{x'} = \textsf{b}$, namely:

$\frac{||\Delta \textsf{x}||}{||\textsf{x}||} \le$ cond$(\textsf{A})\frac{||\textsf{E}||}{||\textsf{A}||}$

Example; suppose we have $\textsf{Ax = b}$ given by:

$\begin{bmatrix}
1&2&2\\4&4&2\\4&6&4
\end{bmatrix} \begin{bmatrix}
x_1\\x_2\\x_3
\end{bmatrix}=\begin{bmatrix}
3\\6\\10
\end{bmatrix}$

Where the solution of the system is given by $\textsf{x} = \begin{bmatrix}
-1&3&-1\end{bmatrix}^{\textsf{T}}$. If a perturbation/anomaly $\Delta \textsf{b} = \begin{bmatrix}
-1.8&0&0\end{bmatrix}^{\textsf{T}}$ is applied to the vector $\textsf{b}$, the linear system to be solved becomes:

$\begin{bmatrix}
1&2&2\\4&4&2\\4&6&4
\end{bmatrix} \begin{bmatrix}
x'_1\\x'_2\\x'_3
\end{bmatrix}=\begin{bmatrix}
1.2\\6\\10
\end{bmatrix}$

This system has a solution $\textsf{x'} = \begin{bmatrix}
-2.8&6.6&-4.6\end{bmatrix}^{\textsf{T}}$, and so the difference between the two solutions is given by:

$\Delta \textsf{x} = \textsf{x'} - \textsf{x} = \begin{bmatrix}
-1.8\\3.6\\-3.6\end{bmatrix} \implies \frac{||\Delta \textsf{x}||_1}{||\textsf{x}||_1} = 1.8$

While:

$\frac{||\Delta \textsf{b}||_1}{||\textsf{b}||_1} \approx 0.095$

With cond($\textsf{A}$) $= 60$, the inequality found above becomes:

$1.8 \le 5.68$

Which holds.

#### Residual

The **residual** $\textsf{r}$ of an approximate solution $\textsf{x'}$ of the system $\textsf{Ax = b}$ is defined as:

$\textsf{r}$ = $\textsf{b - Ax'}$

If we multiply the system $\textsf{Ax = b}$ by an arbitrary number, the solution will remain the same, whereas the residual will be multiplied by the same number. Therefore, it only makes sense to work with a relative residual:

$\frac{||\textsf{r}||}{||\textsf{A}||\cdot ||\textsf{x'}||}$

One can relate the error to the residual via:

$\frac{||\Delta \textsf{x}||}{||\textsf{x}||} \le$ cond$(\textsf{A})\frac{||\textsf{r}||}{||\textsf{A}||\cdot ||\textsf{x'}||}$

Therefore, a small residual implies a small relative error in the solution only if the matrix $\textsf{A}$ has a small condition number.

## 2.2 - Linear Least Squares

### Theoretical Background

A method that solves/approximates $\textsf{Ax = b}$ for **x**, where $\textsf{A}$ is *overdetermined*. The method works by minimizing the square of the residual $\textsf{r}$, hence it name. Suppose we're fitting a quadratic polynomial to 6 data points ($t_i,y_i$), then the *overdetermined* problem has the following general form:

$\textsf{Ax} =
\begin{bmatrix}
1&t_1&t_1^2\\
1&t_2&t_2^2\\
1&t_3&t_3^2\\
1&t_4&t_4^2\\
1&t_5&t_5^2\\
1&t_6&t_6^2\\
\end{bmatrix}\begin{bmatrix}
x_1\\x_2\\x_3
\end{bmatrix}=\begin{bmatrix}
y_1\\y_2\\y_3\\y_4\\y_5\\y_6
\end{bmatrix} = \textsf{b}
$

Note that a matrix, such as $\textsf{A}$, where the columns are successive powers of some independent variable is called a *Vandermonde matrix*. Transforming our $t$-data into such a matrix makes sense once you start doing matrix vector multiplication.

qed

### Python

Import the necessary libraries

In [ ]:
import numpy as np
from scipy.linalg import lstsq

Suppose we have 11 data points, a $y$-value for every independent $x$-value.

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([2.9, 4.8, 7.1, 7.7, 9.4, 9.6, 10.2, 8.3, 9.0, 6.6, 4.1])

We want to fit a quadratic polynomial to our data, hence we must transform our $x$-data into a *Vandermonde matrix*.

In [ ]:
M = x[:, np.newaxis]**[0,1,2]
print(M)

[[  1   0   0]
 [  1   1   1]
 [  1   2   4]
 [  1   3   9]
 [  1   4  16]
 [  1   5  25]
 [  1   6  36]
 [  1   7  49]
 [  1   8  64]
 [  1   9  81]
 [  1  10 100]]


In [ ]:
# We want to find the least-squares solution to M.dot(p) = y,
# where p is a vector with length 3 that holds the parameters a and b an c.
p, res, rnk, s = lstsq(M, y)

print(p)

[ 2.6048951   2.65037296 -0.2460373 ]
